name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-angular-cli:
    name: Build Monorepo (Angular CLI)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./angular-cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Log results
        run: tree ./dist
  build-nx:
    name: Build Monorepo (NX)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./nx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Log results
        run: tree ./dist
