name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-angular-cli:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0
      - name: Switch directory
        run: cd ./angular-cli
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Log results
        run: tree ./dist
  build-nx:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0
      - name: Switch directory
        run: cd ./nx
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Log results
        run: tree ./dist
